#!/usr/bin/env python3
"""
Parse voice list from markdown tables and output CSV filtered by:
- 通用场景 (general scenario)
- 短剧场景 (short drama / 角色扮演, S2S-SC)
- 英文语种 (English: 美式英语, 英式英语, 澳洲英语, 英语)
"""

import csv
import re

# Raw table rows extracted from the voice list (场景, 音色名称, voice_type, 语种, ...)
# Format: (场景, 音色名称, voice_type, 语种, extra...)
VOICE_ROWS = [
    # 豆包语音合成模型2.0
    ("通用场景", "Vivi 2.0", "zh_female_vv_uranus_bigtts", "中文、英语、日文、印尼、墨西哥"),
    ("通用场景", "小何 2.0", "zh_female_xiaohe_uranus_bigtts", "中文"),
    ("通用场景", "云舟 2.0", "zh_male_m191_uranus_bigtts", "中文"),
    ("通用场景", "小天 2.0", "zh_male_taocheng_uranus_bigtts", "中文"),
    ("有声阅读", "儿童绘本", "zh_female_xueayi_saturn_bigtts", "中文"),
    ("视频配音", "大壹", "zh_male_dayi_saturn_bigtts", "中文"),
    ("视频配音", "黑猫侦探社咪", "zh_female_mizai_saturn_bigtts", "中文"),
    ("视频配音", "鸡汤女", "zh_female_jitangnv_saturn_bigtts", "中文"),
    ("视频配音", "魅力女友", "zh_female_meilinvyou_saturn_bigtts", "中文"),
    ("视频配音", "流畅女声", "zh_female_santongyongns_saturn_bigtts", "中文"),
    ("视频配音", "儒雅逸辰", "zh_male_ruyayichen_saturn_bigtts", "中文"),
    ("角色扮演", "可爱女生", "saturn_zh_female_keainvsheng_tob", "中文"),
    ("角色扮演", "调皮公主", "saturn_zh_female_tiaopigongzhu_tob", "中文"),
    ("角色扮演", "爽朗少年", "saturn_zh_male_shuanglangshaonian_tob", "中文"),
    ("角色扮演", "天才同桌", "saturn_zh_male_tiancaitongzhuo_tob", "中文"),
    ("角色扮演", "知性灿灿", "saturn_zh_female_cancan_tob", "中文"),
    ("客服场景", "轻盈朵朵 2.0", "saturn_zh_female_qingyingduoduo_cs_tob", "中文"),
    ("客服场景", "温婉珊珊 2.0", "saturn_zh_female_wenwanshanshan_cs_tob", "中文"),
    ("客服场景", "热情艾娜 2.0", "saturn_zh_female_reqingaina_cs_tob", "中文"),
    ("多语种", "Tim", "en_male_tim_uranus_bigtts", "美式英语"),
    ("多语种", "Dacey", "en_female_dacey_uranus_bigtts", "美式英语"),
    ("多语种", "Stokie", "en_female_stokie_uranus_bigtts", "美式英语"),
    # 端到端实时语音大模型-O版本
    ("S2S-Omni", "vivi", "zh_female_vv_jupiter_bigtts", "中文"),
    ("S2S-Omni", "小何", "zh_female_xiaohe_jupiter_bigtts", "中文"),
    ("S2S-Omni", "云舟", "zh_male_yunzhou_jupiter_bigtts", "中文"),
    ("S2S-Omni", "小天", "zh_male_xiaotian_jupiter_bigtts", "中文"),
    # 豆包语音合成模型1.0 - 多情感
    ("多情感", "冷酷哥哥（多情感）", "zh_male_lengkugege_emo_v2_mars_bigtts", "中文"),
    ("多情感", "甜心小美（多情感）", "zh_female_tianxinxiaomei_emo_v2_mars_bigtts", "中文"),
    ("多情感", "高冷御姐（多情感）", "zh_female_gaolengyujie_emo_v2_mars_bigtts", "中文"),
    ("多情感", "傲娇霸总（多情感）", "zh_male_aojiaobazong_emo_v2_mars_bigtts", "中文"),
    ("多情感", "广州德哥（多情感）", "zh_male_guangzhoudege_emo_mars_bigtts", "中文"),
    ("多情感", "京腔侃爷（多情感）", "zh_male_jingqiangkanye_emo_mars_bigtts", "中文"),
    ("多情感", "邻居阿姨（多情感）", "zh_female_linjuayi_emo_v2_mars_bigtts", "中文"),
    ("多情感", "优柔公子（多情感）", "zh_male_yourougongzi_emo_v2_mars_bigtts", "中文"),
    ("多情感", "儒雅男友（多情感）", "zh_male_ruyayichen_emo_v2_mars_bigtts", "中文"),
    ("多情感", "俊朗男友（多情感）", "zh_male_junlangnanyou_emo_v2_mars_bigtts", "中文"),
    ("多情感", "北京小爷（多情感）", "zh_male_beijingxiaoye_emo_v2_mars_bigtts", "中文"),
    ("多情感", "柔美女友（多情感）", "zh_female_roumeinvyou_emo_v2_mars_bigtts", "中文"),
    ("多情感", "阳光青年（多情感）", "zh_male_yangguangqingnian_emo_v2_mars_bigtts", "中文"),
    ("多情感", "魅力女友（多情感）", "zh_female_meilinvyou_emo_v2_mars_bigtts", "中文"),
    ("多情感", "爽快思思（多情感）", "zh_female_shuangkuaisisi_emo_v2_mars_bigtts", "中文,英式英语"),
    ("多情感", "Candice", "en_female_candice_emo_v2_mars_bigtts", "美式英语"),
    ("多情感", "Serena", "en_female_skye_emo_v2_mars_bigtts", "美式英语"),
    ("多情感", "Glen", "en_male_glen_emo_v2_mars_bigtts", "美式英语"),
    ("多情感", "Sylus", "en_male_sylus_emo_v2_mars_bigtts", "美式英语"),
    ("多情感", "Corey", "en_male_corey_emo_v2_mars_bigtts", "英式英语"),
    ("多情感", "Nadia", "en_female_nadia_tips_emo_v2_mars_bigtts", "英式英语"),
    ("多情感", "深夜播客", "zh_male_shenyeboke_emo_v2_mars_bigtts", "中文"),
    ("教育场景", "Tina老师", "zh_female_yingyujiaoyu_mars_bigtts", "中文,英式英语"),  # 含英文，保留
    # 通用场景 1.0
    ("通用场景", "温柔女神", "ICL_zh_female_wenrounvshen_239eff5e8ffa_tob", "中文"),
    ("通用场景", "Vivi", "zh_female_vv_mars_bigtts", "中文"),
    ("通用场景", "亲切女声", "zh_female_qinqienvsheng_moon_bigtts", "中文"),
    ("通用场景", "机灵小伙", "ICL_zh_male_shenmi_v1_tob", "中文"),
    ("通用场景", "元气甜妹", "ICL_zh_female_wuxi_tob", "中文"),
    ("通用场景", "知心姐姐", "ICL_zh_female_wenyinvsheng_v1_tob", "中文"),
    ("通用场景", "阳光阿辰", "zh_male_qingyiyuxuan_mars_bigtts", "中文"),
    ("通用场景", "快乐小东", "zh_male_xudong_conversation_wvae_bigtts", "中文"),
    ("通用场景", "冷酷哥哥", "ICL_zh_male_lengkugege_v1_tob", "中文"),
    ("通用场景", "纯澈女生", "ICL_zh_female_feicui_v1_tob", "中文"),
    ("通用场景", "初恋女友", "ICL_zh_female_yuxin_v1_tob", "中文"),
    ("通用场景", "贴心闺蜜", "ICL_zh_female_xnx_tob", "中文"),
    ("通用场景", "温柔白月光", "ICL_zh_female_yry_tob", "中文"),
    ("通用场景", "炀炀", "ICL_zh_male_BV705_streaming_cs_tob", "中文"),
    ("通用场景", "开朗学长", "en_male_jason_conversation_wvae_bigtts", "中文"),
    ("通用场景", "魅力苏菲", "zh_female_sophie_conversation_wvae_bigtts", "中文"),
    ("通用场景", "贴心妹妹", "ICL_zh_female_yilin_tob", "中文"),
    ("通用场景", "甜美桃子", "zh_female_tianmeitaozi_mars_bigtts", "中文"),
    ("通用场景", "清新女声", "zh_female_qingxinnvsheng_mars_bigtts", "中文"),
    ("通用场景", "知性女声", "zh_female_zhixingnvsheng_mars_bigtts", "中文"),
    ("通用场景", "清爽男大", "zh_male_qingshuangnanda_mars_bigtts", "中文"),
    ("通用场景", "邻家女孩", "zh_female_linjianvhai_moon_bigtts", "中文"),
    ("通用场景", "渊博小叔", "zh_male_yuanboxiaoshu_moon_bigtts", "中文"),
    ("通用场景", "阳光青年", "zh_male_yangguangqingnian_moon_bigtts", "中文"),
    ("通用场景", "甜美小源", "zh_female_tianmeixiaoyuan_moon_bigtts", "中文"),
    ("通用场景", "清澈梓梓", "zh_female_qingchezizi_moon_bigtts", "中文"),
    ("通用场景", "解说小明", "zh_male_jieshuoxiaoming_moon_bigtts", "中文"),
    ("通用场景", "开朗姐姐", "zh_female_kailangjiejie_moon_bigtts", "中文"),
    ("通用场景", "邻家男孩", "zh_male_linjiananhai_moon_bigtts", "中文"),
    ("通用场景", "甜美悦悦", "zh_female_tianmeiyueyue_moon_bigtts", "中文"),
    ("通用场景", "心灵鸡汤", "zh_female_xinlingjitang_moon_bigtts", "中文"),
    ("通用场景", "知性温婉", "ICL_zh_female_zhixingwenwan_tob", "中文"),
    ("通用场景", "暖心体贴", "ICL_zh_male_nuanxintitie_tob", "中文"),
    ("通用场景", "开朗轻快", "ICL_zh_male_kailangqingkuai_tob", "中文"),
    ("通用场景", "活泼爽朗", "ICL_zh_male_huoposhuanglang_tob", "中文"),
    ("通用场景", "率真小伙", "ICL_zh_male_shuaizhenxiaohuo_tob", "中文"),
    ("通用场景", "温柔小哥", "zh_male_wenrouxiaoge_mars_bigtts", "中文"),
    ("通用场景", "灿灿/Shiny", "zh_female_cancan_mars_bigtts", "中文,美式英语"),
    ("通用场景", "爽快思思/Skye", "zh_female_shuangkuaisisi_moon_bigtts", "中文,美式英语"),
    ("通用场景", "温暖阿虎/Alvin", "zh_male_wennuanahu_moon_bigtts", "中文,美式英语"),
    ("通用场景", "少年梓辛/Brayan", "zh_male_shaonianzixin_moon_bigtts", "中文,美式英语"),
    ("通用场景、S2S-SC", "温柔文雅", "ICL_zh_female_wenrouwenya_tob", "中文"),
    ("IP仿音", "沪普男", "zh_male_hupunan_mars_bigtts", "仅中文"),
    ("IP仿音", "鲁班七号", "zh_male_lubanqihao_mars_bigtts", "仅中文"),
    ("IP仿音", "林潇", "zh_female_yangmi_mars_bigtts", "仅中文"),
    ("IP仿音", "玲玲姐姐", "zh_female_linzhiling_mars_bigtts", "仅中文"),
    ("IP仿音", "春日部姐姐", "zh_female_jiyejizi2_mars_bigtts", "仅中文"),
    ("IP仿音", "唐僧", "zh_male_tangseng_mars_bigtts", "仅中文"),
    ("IP仿音", "庄周", "zh_male_zhuangzhou_mars_bigtts", "仅中文"),
    ("IP仿音", "猪八戒", "zh_male_zhubajie_mars_bigtts", "仅中文"),
    ("IP仿音", "感冒电音姐姐", "zh_female_ganmaodianyin_mars_bigtts", "仅中文"),
    ("IP仿音", "直率英子", "zh_female_naying_mars_bigtts", "仅中文"),
    ("IP仿音", "女雷神", "zh_female_leidian_mars_bigtts", "仅中文"),
    ("趣味口音", "粤语小溏", "zh_female_yueyunv_mars_bigtts", "中文"),
    ("趣味口音", "豫州子轩", "zh_male_yuzhouzixuan_moon_bigtts", "中文-河南口音"),
    ("趣味口音", "呆萌川妹", "zh_female_daimengchuanmei_moon_bigtts", "中文-四川口音"),
    ("趣味口音", "广西远舟", "zh_male_guangxiyuanzhou_moon_bigtts", "中文-广西口音"),
    ("趣味口音", "双节棍小哥", "zh_male_zhoujielun_emo_v2_mars_bigtts", "中文-台湾口音"),
    ("趣味口音", "湾湾小何", "zh_female_wanwanxiaohe_moon_bigtts", "中文-台湾口音"),
    ("趣味口音", "湾区大叔", "zh_female_wanqudashu_moon_bigtts", "中文-广东口音"),
    ("趣味口音", "广州德哥", "zh_male_guozhoudege_moon_bigtts", "中文-广东口音"),
    ("趣味口音", "浩宇小哥", "zh_male_haoyuxiaoge_moon_bigtts", "中文-青岛口音"),
    ("趣味口音", "北京小爷", "zh_male_beijingxiaoye_moon_bigtts", "中文-北京口音"),
    ("趣味口音", "京腔侃爷/Harmony", "zh_male_jingqiangkanye_moon_bigtts", "中文-北京口音,美式英语"),
    ("趣味口音", "妹坨洁儿", "zh_female_meituojieer_moon_bigtts", "中文-长沙口音"),
    # 角色扮演
    ("角色扮演", "纯真少女", "ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob", "中文"),
    ("角色扮演", "奶气小生", "ICL_zh_male_xiaonaigou_edf58cf28b8b_tob", "中文"),
    ("角色扮演", "精灵向导", "ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob", "中文"),
    ("角色扮演", "闷油瓶小哥", "ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob", "中文"),
    ("角色扮演", "黯刃秦主", "ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob", "中文"),
    ("角色扮演", "霸道总裁", "ICL_zh_male_badaozongcai_v1_tob", "中文"),
    ("角色扮演", "妩媚可人", "ICL_zh_female_ganli_v1_tob", "中文"),
    ("角色扮演", "邪魅御姐", "ICL_zh_female_xiangliangya_v1_tob", "中文"),
    ("角色扮演", "嚣张小哥", "ICL_zh_male_ms_tob", "中文"),
    ("角色扮演", "油腻大叔", "ICL_zh_male_you_tob", "中文"),
    ("角色扮演", "孤傲公子", "ICL_zh_male_guaogongzi_v1_tob", "中文"),
    ("角色扮演", "胡子叔叔", "ICL_zh_male_huzi_v1_tob", "中文"),
    ("角色扮演", "性感魅惑", "ICL_zh_female_luoqing_v1_tob", "中文"),
    ("角色扮演", "病弱公子", "ICL_zh_male_bingruogongzi_tob", "中文"),
    ("角色扮演", "邪魅女王", "ICL_zh_female_bingjiao3_tob", "中文"),
    ("角色扮演", "傲慢青年", "ICL_zh_male_aomanqingnian_tob", "中文"),
    ("角色扮演", "醋精男生", "ICL_zh_male_cujingnansheng_tob", "中文"),
    ("角色扮演", "爽朗少年", "ICL_zh_male_shuanglangshaonian_tob", "中文"),
    ("角色扮演", "撒娇男友", "ICL_zh_male_sajiaonanyou_tob", "中文"),
    ("角色扮演", "温柔男友", "ICL_zh_male_wenrounanyou_tob", "中文"),
    ("角色扮演", "温顺少年", "ICL_zh_male_wenshunshaonian_tob", "中文"),
    ("角色扮演", "粘人男友", "ICL_zh_male_naigounanyou_tob", "中文"),
    ("角色扮演", "撒娇男生", "ICL_zh_male_sajiaonansheng_tob", "中文"),
    ("角色扮演", "活泼男友", "ICL_zh_male_huoponanyou_tob", "中文"),
    ("角色扮演", "甜系男友", "ICL_zh_male_tianxinanyou_tob", "中文"),
    ("角色扮演", "活力青年", "ICL_zh_male_huoliqingnian_tob", "中文"),
    ("角色扮演", "开朗青年", "ICL_zh_male_kailangqingnian_tob", "中文"),
    ("角色扮演", "冷漠兄长", "ICL_zh_male_lengmoxiongzhang_tob", "中文"),
    ("角色扮演", "天才同桌", "ICL_zh_male_tiancaitongzhuo_tob", "中文"),
    ("角色扮演", "翩翩公子", "ICL_zh_male_pianpiangongzi_tob", "中文"),
    ("角色扮演", "懵懂青年", "ICL_zh_male_mengdongqingnian_tob", "中文"),
    ("角色扮演", "冷脸兄长", "ICL_zh_male_lenglianxiongzhang_tob", "中文"),
    ("角色扮演", "病娇少年", "ICL_zh_male_bingjiaoshaonian_tob", "中文"),
    ("角色扮演", "病娇男友", "ICL_zh_male_bingjiaonanyou_tob", "中文"),
    ("角色扮演", "病弱少年", "ICL_zh_male_bingruoshaonian_tob", "中文"),
    ("角色扮演", "意气少年", "ICL_zh_male_yiqishaonian_tob", "中文"),
    ("角色扮演", "干净少年", "ICL_zh_male_ganjingshaonian_tob", "中文"),
    ("角色扮演", "冷漠男友", "ICL_zh_male_lengmonanyou_tob", "中文"),
    ("角色扮演", "精英青年", "ICL_zh_male_jingyingqingnian_tob", "中文"),
    ("角色扮演", "热血少年", "ICL_zh_male_rexueshaonian_tob", "中文"),
    ("角色扮演", "清爽少年", "ICL_zh_male_qingshuangshaonian_tob", "中文"),
    ("角色扮演", "中二青年", "ICL_zh_male_zhongerqingnian_tob", "中文"),
    ("角色扮演", "凌云青年", "ICL_zh_male_lingyunqingnian_tob", "中文"),
    ("角色扮演", "自负青年", "ICL_zh_male_zifuqingnian_tob", "中文"),
    ("角色扮演", "不羁青年", "ICL_zh_male_bujiqingnian_tob", "中文"),
    ("角色扮演", "儒雅君子", "ICL_zh_male_ruyajunzi_tob", "中文"),
    ("角色扮演", "低音沉郁", "ICL_zh_male_diyinchenyu_tob", "中文"),
    ("角色扮演", "冷脸学霸", "ICL_zh_male_lenglianxueba_tob", "中文"),
    ("角色扮演", "儒雅总裁", "ICL_zh_male_ruyazongcai_tob", "中文"),
    ("角色扮演", "深沉总裁", "ICL_zh_male_shenchenzongcai_tob", "中文"),
    ("角色扮演", "小侯爷", "ICL_zh_male_xiaohouye_tob", "中文"),
    ("角色扮演", "孤高公子", "ICL_zh_male_gugaogongzi_tob", "中文"),
    ("角色扮演", "仗剑君子", "ICL_zh_male_zhangjianjunzi_tob", "中文"),
    ("角色扮演", "温润学者", "ICL_zh_male_wenrunxuezhe_tob", "中文"),
    ("角色扮演", "亲切青年", "ICL_zh_male_qinqieqingnian_tob", "中文"),
    ("角色扮演", "温柔学长", "ICL_zh_male_wenrouxuezhang_tob", "中文"),
    ("角色扮演", "高冷总裁", "ICL_zh_male_gaolengzongcai_tob", "中文"),
    ("角色扮演", "冷峻高智", "ICL_zh_male_lengjungaozhi_tob", "中文"),
    ("角色扮演", "孱弱少爷", "ICL_zh_male_chanruoshaoye_tob", "中文"),
    ("角色扮演", "自信青年", "ICL_zh_male_zixinqingnian_tob", "中文"),
    ("角色扮演", "青涩青年", "ICL_zh_male_qingseqingnian_tob", "中文"),
    ("角色扮演", "学霸同桌", "ICL_zh_male_xuebatongzhuo_tob", "中文"),
    ("角色扮演", "冷傲总裁", "ICL_zh_male_lengaozongcai_tob", "中文"),
    ("角色扮演", "元气少年", "ICL_zh_male_yuanqishaonian_tob", "中文"),
    ("角色扮演", "洒脱青年", "ICL_zh_male_satuoqingnian_tob", "中文"),
    ("角色扮演", "直率青年", "ICL_zh_male_zhishuaiqingnian_tob", "中文"),
    ("角色扮演", "斯文青年", "ICL_zh_male_siwenqingnian_tob", "中文"),
    ("角色扮演", "俊逸公子", "ICL_zh_male_junyigongzi_tob", "中文"),
    ("角色扮演", "仗剑侠客", "ICL_zh_male_zhangjianxiake_tob", "中文"),
    ("角色扮演", "机甲智能", "ICL_zh_male_jijiaozhineng_tob", "中文"),
    ("角色扮演", "奶气萌娃", "zh_male_naiqimengwa_mars_bigtts", "中文"),
    ("角色扮演", "婆婆", "zh_female_popo_mars_bigtts", "中文"),
    ("角色扮演", "高冷御姐", "zh_female_gaolengyujie_moon_bigtts", "中文"),
    ("角色扮演", "傲娇霸总", "zh_male_aojiaobazong_moon_bigtts", "中文"),
    ("角色扮演", "魅力女友", "zh_female_meilinvyou_moon_bigtts", "中文"),
    ("角色扮演", "深夜播客", "zh_male_shenyeboke_moon_bigtts", "中文"),
    ("角色扮演", "柔美女友", "zh_female_sajiaonvyou_moon_bigtts", "中文"),
    ("角色扮演", "撒娇学妹", "zh_female_yuanqinvyou_moon_bigtts", "中文"),
    ("角色扮演", "病弱少女", "ICL_zh_female_bingruoshaonv_tob", "中文"),
    ("角色扮演", "活泼女孩", "ICL_zh_female_huoponvhai_tob", "中文"),
    ("角色扮演", "东方浩然", "zh_male_dongfanghaoran_moon_bigtts", "中文"),
    ("角色扮演", "绿茶小哥", "ICL_zh_male_lvchaxiaoge_tob", "中文"),
    ("角色扮演", "娇弱萝莉", "ICL_zh_female_jiaoruoluoli_tob", "中文"),
    ("角色扮演", "冷淡疏离", "ICL_zh_male_lengdanshuli_tob", "中文"),
    ("角色扮演", "憨厚敦实", "ICL_zh_male_hanhoudunshi_tob", "中文"),
    ("角色扮演", "活泼刁蛮", "ICL_zh_female_huopodiaoman_tob", "中文"),
    ("角色扮演", "固执病娇", "ICL_zh_male_guzhibingjiao_tob", "中文"),
    ("角色扮演", "撒娇粘人", "ICL_zh_male_sajiaonianren_tob", "中文"),
    ("角色扮演", "傲慢娇声", "ICL_zh_female_aomanjiaosheng_tob", "中文"),
    ("角色扮演", "潇洒随性", "ICL_zh_male_xiaosasuixing_tob", "中文"),
    ("角色扮演", "诡异神秘", "ICL_zh_male_guiyishenmi_tob", "中文"),
    ("角色扮演", "儒雅才俊", "ICL_zh_male_ruyacaijun_tob", "中文"),
    ("角色扮演", "正直青年", "ICL_zh_male_zhengzhiqingnian_tob", "中文"),
    ("角色扮演", "娇憨女王", "ICL_zh_female_jiaohannvwang_tob", "中文"),
    ("角色扮演", "病娇萌妹", "ICL_zh_female_bingjiaomengmei_tob", "中文"),
    ("角色扮演", "青涩小生", "ICL_zh_male_qingsenaigou_tob", "中文"),
    ("角色扮演", "纯真学弟", "ICL_zh_male_chunzhenxuedi_tob", "中文"),
    ("角色扮演", "优柔帮主", "ICL_zh_male_youroubangzhu_tob", "中文"),
    ("角色扮演", "优柔公子", "ICL_zh_male_yourougongzi_tob", "中文"),
    ("角色扮演", "调皮公主", "ICL_zh_female_tiaopigongzhu_tob", "中文"),
    ("角色扮演", "贴心男友", "ICL_zh_male_tiexinnanyou_tob", "中文"),
    ("角色扮演", "少年将军", "ICL_zh_male_shaonianjiangjun_tob", "中文"),
    ("角色扮演", "病娇哥哥", "ICL_zh_male_bingjiaogege_tob", "中文"),
    ("角色扮演", "学霸男同桌", "ICL_zh_male_xuebanantongzhuo_tob", "中文"),
    ("角色扮演", "幽默叔叔", "ICL_zh_male_youmoshushu_tob", "中文"),
    ("角色扮演", "假小子", "ICL_zh_female_jiaxiaozi_tob", "中文"),
    ("角色扮演", "温柔男同桌", "ICL_zh_male_wenrounantongzhuo_tob", "中文"),
    ("角色扮演", "幽默大爷", "ICL_zh_male_youmodaye_tob", "中文"),
    ("角色扮演", "枕边低语", "ICL_zh_male_asmryexiu_tob", "中文"),
    ("角色扮演", "神秘法师", "ICL_zh_male_shenmifashi_tob", "中文"),
    ("角色扮演", "娇喘女声", "zh_female_jiaochuan_mars_bigtts", "仅中文"),
    ("角色扮演", "开朗弟弟", "zh_male_livelybro_mars_bigtts", "仅中文"),
    ("角色扮演", "谄媚女声", "zh_female_flattery_mars_bigtts", "仅中文"),
    ("角色扮演", "冷峻上司", "ICL_zh_male_lengjunshangsi_tob", "中文"),
    ("角色扮演", "寡言小哥", "ICL_zh_male_xiaoge_v1_tob", "中文"),
    ("角色扮演", "清朗温润", "ICL_zh_male_renyuwangzi_v1_tob", "中文"),
    ("角色扮演", "潇洒随性", "ICL_zh_male_xiaosha_v1_tob", "中文"),
    ("角色扮演", "清冷矜贵", "ICL_zh_male_liyisheng_v1_tob", "中文"),
    ("角色扮演", "沉稳优雅", "ICL_zh_male_qinglen_v1_tob", "中文"),
    ("角色扮演", "清逸苏感", "ICL_zh_male_chongqingzhanzhan_v1_tob", "中文"),
    ("角色扮演", "温柔内敛", "ICL_zh_male_xingjiwangzi_v1_tob", "中文"),
    ("角色扮演", "低沉缱绻", "ICL_zh_male_sigeshiye_v1_tob", "中文"),
    ("角色扮演", "蓝银草魂师", "ICL_zh_male_lanyingcaohunshi_v1_tob", "中文"),
    ("角色扮演", "清冷高雅", "ICL_zh_female_liumengdie_v1_tob", "中文"),
    ("角色扮演", "甜美娇俏", "ICL_zh_female_linxueying_v1_tob", "中文"),
    ("角色扮演", "柔骨魂师", "ICL_zh_female_rouguhunshi_v1_tob", "中文"),
    ("角色扮演", "甜美活泼", "ICL_zh_female_tianmei_v1_tob", "中文"),
    ("角色扮演", "成熟温柔", "ICL_zh_female_chengshu_v1_tob", "中文"),
    ("角色扮演", "贴心闺蜜", "ICL_zh_female_xnx_v1_tob", "中文"),
    ("角色扮演", "温柔白月光", "ICL_zh_female_yry_v1_tob", "中文"),
    ("角色扮演", "高冷沉稳", "zh_male_bv139_audiobook_ummv3_bigtts", "中文"),
    # 角色扮演、S2S-SC (短剧)
    ("角色扮演、S2S-SC", "醋精男友", "ICL_zh_male_cujingnanyou_tob", "中文"),
    ("角色扮演、S2S-SC", "风发少年", "ICL_zh_male_fengfashaonian_tob", "中文"),
    ("角色扮演、S2S-SC", "磁性男嗓", "ICL_zh_male_cixingnansang_tob", "中文"),
    ("角色扮演、S2S-SC", "成熟总裁", "ICL_zh_male_chengshuzongcai_tob", "中文"),
    ("角色扮演、S2S-SC", "傲娇精英", "ICL_zh_male_aojiaojingying_tob", "中文"),
    ("角色扮演、S2S-SC", "傲娇公子", "ICL_zh_male_aojiaogongzi_tob", "中文"),
    ("角色扮演、S2S-SC", "霸道少爷", "ICL_zh_male_badaoshaoye_tob", "中文"),
    ("角色扮演、S2S-SC", "腹黑公子", "ICL_zh_male_fuheigongzi_tob", "中文"),
    ("角色扮演、S2S-SC", "暖心学姐", "ICL_zh_female_nuanxinxuejie_tob", "中文"),
    ("角色扮演、S2S-SC", "可爱女生", "ICL_zh_female_keainvsheng_tob", "中文"),
    ("角色扮演、S2S-SC", "成熟姐姐", "ICL_zh_female_chengshujiejie_tob", "中文"),
    ("角色扮演、S2S-SC", "病娇姐姐", "ICL_zh_female_bingjiaojiejie_tob", "中文"),
    ("角色扮演、S2S-SC", "妩媚御姐", "ICL_zh_female_wumeiyujie_tob", "中文"),
    ("角色扮演、S2S-SC", "傲娇女友", "ICL_zh_female_aojiaonvyou_tob", "中文"),
    ("角色扮演、S2S-SC", "贴心女友", "ICL_zh_female_tiexinnvyou_tob", "中文"),
    ("角色扮演、S2S-SC", "性感御姐", "ICL_zh_female_xingganyujie_tob", "中文"),
    ("角色扮演、S2S-SC", "病娇弟弟", "ICL_zh_male_bingjiaodidi_tob", "中文"),
    ("角色扮演、S2S-SC", "傲慢少爷", "ICL_zh_male_aomanshaoye_tob", "中文"),
    ("角色扮演、S2S-SC", "傲气凌人", "ICL_zh_male_aiqilingren_tob", "中文"),
    ("角色扮演、S2S-SC", "病娇白莲", "ICL_zh_male_bingjiaobailian_tob", "中文"),
    # 多语种 - 英文
    ("多语种", "Lauren", "en_female_lauren_moon_bigtts", "美式英语"),
    ("多语种", "Energetic Male II", "en_male_campaign_jamal_moon_bigtts", "美式英语"),
    ("多语种", "Gotham Hero", "en_male_chris_moon_bigtts", "美式英语"),
    ("多语种", "Flirty Female", "en_female_product_darcie_moon_bigtts", "美式英语"),
    ("多语种", "Peaceful Female", "en_female_emotional_moon_bigtts", "美式英语"),
    ("多语种", "Nara", "en_female_nara_moon_bigtts", "美式英语"),
    ("多语种", "Bruce", "en_male_bruce_moon_bigtts", "美式英语"),
    ("多语种", "Michael", "en_male_michael_moon_bigtts", "美式英语"),
    ("多语种", "Cartoon Chef", "ICL_en_male_cc_sha_v1_tob", "美式英语"),
    ("多语种", "Lucas", "zh_male_M100_conversation_wvae_bigtts", "美式英语"),
    ("多语种", "Sophie", "zh_female_sophie_conversation_wvae_bigtts", "美式英语"),
    ("多语种", "Daisy", "en_female_dacey_conversation_wvae_bigtts", "美式英语"),
    ("多语种", "Owen", "en_male_charlie_conversation_wvae_bigtts", "美式英语"),
    ("多语种", "Luna", "en_female_sarah_new_conversation_wvae_bigtts", "美式英语"),
    ("多语种", "Michael", "ICL_en_male_michael_tob", "美式英语"),
    ("多语种", "Charlie", "ICL_en_female_cc_cm_v1_tob", "美式英语"),
    ("多语种", "Big Boogie", "ICL_en_male_oogie2_tob", "美式英语"),
    ("多语种", "Frosty Man", "ICL_en_male_frosty1_tob", "美式英语"),
    ("多语种", "The Grinch", "ICL_en_male_grinch2_tob", "美式英语"),
    ("多语种", "Zayne", "ICL_en_male_zayne_tob", "美式英语"),
    ("多语种", "Jigsaw", "ICL_en_male_cc_jigsaw_tob", "美式英语"),
    ("多语种", "Chucky", "ICL_en_male_cc_chucky_tob", "美式英语"),
    ("多语种", "Clown Man", "ICL_en_male_cc_penny_v1_tob", "美式英语"),
    ("多语种", "Kevin McCallister", "ICL_en_male_kevin2_tob", "美式英语"),
    ("多语种", "Xavier", "ICL_en_male_xavier1_v1_tob", "美式英语"),
    ("多语种", "Noah", "ICL_en_male_cc_dracula_v1_tob", "美式英语"),
    ("多语种", "Adam", "en_male_adam_mars_bigtts", "美式英语"),
    ("多语种", "Amanda", "en_female_amanda_mars_bigtts", "美式英语"),
    ("多语种", "Jackson", "en_male_jackson_mars_bigtts", "美式英语"),
    ("多语种", "Delicate Girl", "en_female_daisy_moon_bigtts", "英式英语"),
    ("多语种", "Dave", "en_male_dave_moon_bigtts", "英式英语"),
    ("多语种", "Hades", "en_male_hades_moon_bigtts", "英式英语"),
    ("多语种", "Onez", "en_female_onez_moon_bigtts", "英式英语"),
    ("多语种", "Emily", "en_female_emily_mars_bigtts", "英式英语"),
    ("多语种", "Daniel", "zh_male_xudong_conversation_wvae_bigtts", "英式英语"),
    ("多语种", "Alastor", "ICL_en_male_cc_alastor_tob", "英式英语"),
    ("多语种", "Smith", "en_male_smith_mars_bigtts", "英式英语"),
    ("多语种", "Anna", "en_female_anna_mars_bigtts", "英式英语"),
    ("多语种", "Ethan", "ICL_en_male_aussie_v1_tob", "澳洲英语"),
    ("多语种", "Sarah", "en_female_sarah_mars_bigtts", "澳洲英语"),
    ("多语种", "Dryw", "en_male_dryw_mars_bigtts", "澳洲英语"),
]

# English keywords in 语种
ENGLISH_LANG = ("美式英语", "英式英语", "澳洲英语", "英语")


def is_general(scene: str) -> bool:
    return "通用场景" in scene


def is_short_drama(scene: str) -> bool:
    """短剧场景：角色扮演、S2S-SC"""
    return "角色扮演" in scene or "S2S-SC" in scene


def is_english_lang(lang: str) -> bool:
    return any(eng in lang for eng in ENGLISH_LANG)


def keep_row(scene: str, lang: str) -> bool:
    return is_general(scene) or is_short_drama(scene) or is_english_lang(lang)


def main():
    filtered = [
        (scene, name, voice_type, lang)
        for (scene, name, voice_type, lang) in VOICE_ROWS
        if keep_row(scene, lang)
    ]
    out_path = "/Users/skyfalling/Workspace/express/python/pikppo/docs/voice_list_filtered.csv"
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["场景", "音色名称", "voice_type", "语种"])
        w.writerows(filtered)
    print(f"Total rows in source: {len(VOICE_ROWS)}")
    print(f"Filtered rows (通用/短剧/英文): {len(filtered)}")
    print(f"Written to: {out_path}")


if __name__ == "__main__":
    main()
